version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ztbd25_mysql
    environment:
      MYSQL_DATABASE: arrpwa_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/static/arrpwa_db_v3.sql:/docker-entrypoint-initdb.d/arrpwa_db_v3.sql


#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dormitory-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/arrpwa_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - dormitory-net

volumes:
  mysql_data:

networks:
  dormitory-net:
    driver: bridge